apiVersion: v1
kind: Pod
metadata:
  name: k8s-socketcan-client-example
spec:
  containers:
  - image: ghcr.io/collabora/alpine-can:main
    command:
    - /bin/sh
    - -c
    - tail -f /dev/null
    imagePullPolicy: Always
    name: k8s-socketcan-client-example
    resources:
      limits:
        k8s.collabora.com/vcan: 2
  tolerations:
  - key: "sku"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
