apiVersion: v1
kind: Pod
metadata:
  name: k8s-socketcan-client-example
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - apk add can-utils && tail -f /dev/null
    image: alpine
    imagePullPolicy: Always
    name: k8s-socketcan-client-example
    resources:
      limits:
        k8s.collabora.com/socketcan: 2
  tolerations:
  - key: "sku"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
