name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}

  test:
    needs: build
    name: Test the release on MicroK8s
    runs-on: ubuntu-latest
    steps:
    - uses: balchua/microk8s-actions@v0.2.1
      with:
        channel: '1.19/stable'
        addons: '["dns"]'
    - name: Test k8s-socketcan
      run: |
        kubectl apply -f https://raw.githubusercontent.com/Collabora/k8s-socketcan/main/k8s-socketcan-daemonset.yaml
        kubectl wait --for=condition=ready pod -l name=k8s-socketcan
        kubectl apply -f https://raw.githubusercontent.com/Collabora/k8s-socketcan/main/k8s-socketcan-client-example.yaml
        kubectl wait --for=condition=ready pod k8s-socketcan-client-example
        kubectl get pods -A -o wide
        (sleep 1 && kubectl exec -it k8s-socketcan-client-example -- cansend vcan0 5A1#11.2233.44556677.88) &
        kubectl exec -it k8s-socketcan-client-example -- candump vcan0 -n 1 -T 5000
    - name: Setup tmate session
      if: ${{ failure() }}
      run: |
        curl -L -O https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz
        tar --strip-components=1 -xf tmate-2.4.0-static-linux-amd64.tar.xz
        ./tmate
